apiVersion: v1
kind: page
spec:
  id: 2413lvx
  title: medianTimeToCompletion
  parameters:
    - name: repoId
      value: "23083156"
  content:
    - component: PageRow
      name: pageRow2
      children:
        - component: Text
          name: text1
          props:
            value: "This issue is for:
              [https://www.notion.so/mui-org/KPIs-1ce9658b85ce4628a2a2ed2ae74ff\
              69c?pvs=4#6585efdaa9d24a66a60a2e74e1613cae](https://www.notion.so\
              /mui-org/KPIs-1ce9658b85ce4628a2a2ed2ae74ff69c?pvs=4#6585efdaa9d2\
              4a66a60a2e74e1613cae)"
            mode: markdown
    - component: PageRow
      name: pageRow
      children:
        - component: codeComponent.HealthBadge
          name: codeComponent_HealthBadge
          props:
            value:
              $$jsExpression: |
                (() => {
                  const timeSpanInMonths = 3
                  let totalOpened = 0
                  let totalClosed = 0

                  for (let i = 0; i < timeSpanInMonths; i++) {
                    totalClosed = +issuesOpenedVsClosedRatio.data.data[i].closed
                    totalOpened = +issuesOpenedVsClosedRatio.data.data[i].opened
                  }

                  return (totalOpened / totalClosed).toFixed(2)
                })()
            unit: ratio
            problem: 2
            warning: 2
            lowerIsBetter: true
    - component: PageRow
      name: pageRow1
      children:
        - component: Text
          name: text
          props:
            value:
              $$jsExpression: |
                (() => {
                  return "Based on the last 3 months"
                })()
  queries:
    - name: issuesOpenedVsClosedRatio
      query:
        kind: rest
        url:
          $$jsExpression: >
            `https://api.ossinsight.io/q/analyze-issue-opened-and-closed?repoId=${parameters.repoId}`
        searchParams: []
        headers: []
        method: GET
      parameters:
        - name: repoId
          value:
            $$jsExpression: |
              page.parameters.repoId
  display: shell
