[build]
builder = "NIXPACKS"
watchPatterns = ["**"]
buildCommand = "pnpm build"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "pnpm start"
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 1
