apiVersion: v1
kind: page
spec:
  id: jyhs86t
  title: validatePrioritySupport
  display: standalone
  parameters:
    - name: issueId
      value: ""
    - name: repo
      value: ""
  content:
    - component: PageRow
      name: pageRow1
      children:
        - component: Text
          name: title
          props:
            value: Priority support key validator
            variant: h4
            loading: false
    - component: PageRow
      name: pageRow2
      children:
        - component: TextField
          name: supportKey
          props:
            label: Support Key
            name: supportKey
            variant: outlined
    - component: PageRow
      name: pageRow
      children:
        - component: Text
          name: githubIssueN
          props:
            value:
              $$jsExpression: >
                (() => {
                  if (page.parameters.issueId) {
                    return `Validating priority support key for GitHub issue: ${page.parameters.issueId}`
                  } else {
                    return "GitHub issue not provided!"
                  }
                })()
            variant: subtitle2
    - component: PageRow
      name: pageRow4
      children:
        - component: Container
          name: container
          children:
            - component: PageRow
              name: pageRow5
              children:
                - component: Text
                  name: statusTextLabel
                  props:
                    variant: h6
                    value: "Status:"
                  layout:
                    horizontalAlign: start
                - component: Text
                  name: statusValue
                  props:
                    variant: h6
                    loading: false
                    value:
                      $$jsExpression: |
                        (() => {
                          return updateMuiPaidSupport.data.status
                        })()
                    sx:
                      $$jsExpression: |
                        (() => {
                          if (updateMuiPaidSupport.data.status === "success") {
                            return {
                              color: "green",
                            }
                          } else {
                            return {
                              color: "red",
                            }
                          }
                        })()
  queries:
    - name: updateMuiPaidSupport
      query:
        function: updateMuiPaidSupport
        kind: local
      parameters:
        - name: issueId
          value:
            $$jsExpression: |
              page.parameters.issueId
        - name: repo
          value:
            $$jsExpression: |
              page.parameters.repo
        - name: supportKey
          value:
            $$jsExpression: |
              supportKey.value
