previewsEnabled: true
previewsExpireAfterDays: 3

services:
  - type: web
    name: tools-public
    env: node
    rootDir: tools-public
    buildCommand: corepack enable && pnpm install && pnpm build
    startCommand: pnpm start
    # We use preview environments instead
    pullRequestPreviewsEnabled: false
    plan: starter
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_OPTIONS
        value: --enable-source-maps
      - fromGroup: MUI Store database
      - fromGroup: GitHub public
      - fromGroup: GitHub mui-bot2 public_repo
      - fromGroup: HiBob
      - fromGroup: Zendesk
      - fromGroup: Google Sheet service account
