previewsExpireAfterDays: 3

services:
  - type: web
    name: tools-public
    env: node
    rootDir: tools-public
    buildCommand: yarn && yarn build
    startCommand: yarn start
    pullRequestPreviewsEnabled: true
    plan: standard
    envVars:
      - fromGroup: MUI Store database
