apiVersion: v1
kind: page
spec:
  id: _-clGLR
  title: design_kits_issue_111
  display: shell
  queries:
    - name: query
      query:
        kind: rest
        url: "  https://api.github.com/repos/mui/mui-design-kits/issues/10/reactions"
        headers:
          - name: X-GitHub-Api-Version
            value: 2022-11-28
          - name: Accept
            value: application/vnd.github+json
        method: GET
  content:
    - component: PageRow
      name: pageRow1
      children:
        - component: Text
          name: text
          props:
            value: https://github.com/mui/mui-design-kits/issues/111 upvotes
            variant: h4
    - component: PageRow
      name: pageRow
      children:
        - component: DataGrid
          name: dataGrid
          props:
            rows:
              $$jsExpression: |
                query.data
                  .filter((reaction) => reaction.content === "+1")
                  .map((reaction) => ({ user: reaction.user.html_url }))
            columns:
              - field: user
                type: link
                width: 379
                align: left
            height: 588
