apiVersion: v1
kind: page
spec:
  id: xu1r3hzj
  title: zendeskFirstReply
  content:
    - component: PageRow
      name: pageRow1
      children:
        - component: Text
          name: text
          props:
            value: TBD after we make env variables available in bindings
            sx:
              color: red
    - component: PageRow
      name: pageRow
      children:
        - component: codeComponent.HealthBadge
          name: codeComponent_HealthBadge
          layout:
            columnSize: 1
          props:
            value:
              $$jsExpression: >
                Math.round(
                  (satisfactionRating.data.filter((rating) => rating.score === "good").length /
                    satisfactionRating.data.length) *
                    100
                )
  queries:
    - name: satisfactionRating
      query:
        kind: rest
        url: https://mui.zendesk.com/api/v2/satisfaction_ratings
        searchParams:
          - name: start_time
            value:
              $$jsExpression: >
                (() => {
                  const days = 7 * 3
                  return Math.round(new Date().getTime() / 1000) - 3600 * 24 * days
                })()
          - name: score
            value: received
        headers:
          - name: Authorization
            value: Basic abc
        method: GET
        transform: |-
          return Object.values(data.satisfaction_ratings.reduce((acc, item) => {
            // only keep the latest
            acc[item.ticket_id] = {
              score: item.score,
            };
            return acc;
          }, {}));
        transformEnabled: true
