apiVersion: v1
kind: page
spec:
  id: I1HlSLD
  title: joyUiNpmKpis
  display: shell
  queries:
    - name: queryJoyUIDownloads
      query:
        function: queryJoyUIDownloads
        kind: local
  content:
    - component: PageRow
      name: pageRow
      children:
        - component: codeComponent.NpmChart
          name: codeComponent_NpmChart
          props:
            title: Joy UI npm downloads
            packages:
              $$jsExpression: |
                ["@mui/joy"]
            data:
              $$jsExpression: |
                queryJoyUIDownloads.data
    - component: PageRow
      name: pageRow1
      children:
        - component: codeComponent.NpmChart
          name: codeComponent_NpmChart1
          props:
            data:
              $$jsExpression: |
                queryJoyUIDownloads.data
                  .map((item, idx) => {
                    return {
                      date: item.date,
                      "@mui/joy":
                        idx > 0
                          ? ((item["@mui/joy"] -
                              queryJoyUIDownloads.data[idx - 1]["@mui/joy"]) /
                              queryJoyUIDownloads.data[idx - 1]["@mui/joy"]) *
                            100
                          : null,
                    }
                  })
                  .filter((item) => item["@mui/joy"] !== null)
            packages:
              $$jsExpression: |
                ["@mui/joy"]
            title: Joy UI month to month growth (%)
