apiVersion: v1
kind: page
spec:
  id: m023hp4
  title: npmVersion
  parameters:
    - name: package
      value: react-dom
  content:
    - component: PageRow
      name: pageRow
      children:
        - component: Text
          name: text
          props:
            mode: markdown
            value: >-
              ## Downloads in the last 7 days


              Same data as in https://www.npmjs.com/package/react-dom?activeTab=versions.
    - component: PageRow
      name: pageRow1
      children:
        - component: TextField
          name: textField
          props:
            label: Package
            defaultValue:
              $$jsExpression: |
                page.parameters.package
    - component: PageRow
      name: pageRow2
      children:
        - component: codeComponent.pieChart
          name: codeComponent_pieChart
          props:
            data:
              $$jsExpression: |
                Object.entries(
                  Object.entries(downloadsVersions.data.downloads)
                    .filter(([version]) => version.indexOf("0.0") !== 0)
                    .map((entry) => {
                      const groups = entry[0].split(".")
                      let group = `v${groups[0]}`

                      if (group === "v16" && parseInt(groups[1]) >= 8) {
                        group = "v16.8"
                      }

                      return {
                        version: entry[0],
                        downloads: entry[1],
                        group,
                      }
                    })
                    .reduce((acc, item) => {
                      acc[item.group] |= 0
                      acc[item.group] += item.downloads
                      return acc
                    }, {})
                ).map((group) => ({ name: group[0], value: group[1] }))
  queries:
    - name: downloadsVersions
      query:
        kind: rest
        url:
          $$jsExpression: |
            `https://api.npmjs.org/versions/${encodeURIComponent(
              parameters.package
            )}/last-week`
        headers: []
        method: GET
        transform: return data;
        transformEnabled: false
        searchParams: []
      parameters:
        - name: package
          value:
            $$jsExpression: |
              textField.value
  display: shell
