apiVersion: v1
kind: page
spec:
  id: 39j3h6b
  title: openPRs
  parameters:
    - name: repository
      value: material-ui
  content:
    - component: PageRow
      name: PageRow
      children:
        - component: codeComponent.HealthBadge
          name: codeComponent_HealthBadge
          props:
            value:
              $$jsExpression: |
                openPRs.data.total_count
            unit: " open PRs"
            warning: 50
            problem: 75
            lowerIsBetter: true
  queries:
    - name: openPRs
      query:
        kind: rest
        url: https://api.github.com/search/issues
        searchParams:
          - name: q
            value:
              $$jsExpression: >
                `is:pull-request is:open -is:draft
                repo:mui/${parameters.repository}`
        headers: []
        method: GET
      parameters:
        - name: repository
          value:
            $$jsExpression: |
              page.parameters.repository
  display: standalone
