apiVersion: v1
kind: page
spec:
  id: hj1i3hqe
  title: waitingForMaintainer
  parameters:
    - name: repository
      value: material-ui
  content:
    - component: codeComponent.HealthBadge
      name: codeComponent_HealthBadge
      children: []
      layout:
        columnSize: 1
      props:
        value:
          $$jsExpression: |
            waitingForMaintainer.data.total_count
        warning: 25
        problem: 50
        unit: " issues"
        lowerIsBetter: true
  queries:
    - name: waitingForMaintainer
      query:
        kind: rest
        url: https://api.github.com/search/issues
        searchParams:
          - name: q
            value:
              $$jsExpression: >
                `is:issue is:open repo:mui/${parameters.repository} label:"status: waiting for maintainer" `
        headers: []
        method: GET
      parameters:
        - name: repository
          value:
            $$jsExpression: |
              page.parameters.repository
  display: shell
