apiVersion: v1
kind: page
spec:
  id: lo33hck
  title: Page2
  parameters:
    - name: repository
      value: mui-x
  content:
    - component: PageRow
      name: PageRow
      children:
        - component: codeComponent.HealthBadge
          name: codeComponent_HealthBadge
          props:
            warning: 75
            problem: 50
            value:
              $$jsExpression: >
                Math.round(
                  (queryCommitStatuses.data.repository.defaultBranchRef.target.history.nodes.filter(
                    (commit) =>
                      commit.status &&
                      (commit.status.state === "SUCCESS" || commit.status.state === "PENDING")
                  ).length /
                    queryCommitStatuses.data.repository.defaultBranchRef.target.history.nodes
                      .length) *
                    100
                )
    - component: PageRow
      name: PageRow1
      children:
        - component: Text
          name: Text
          props:
            value:
              $$jsExpression: >
                `Based on the last 7 days
                (${queryCommitStatuses.data.repository.defaultBranchRef.target.history.nodes.length}
                commits)`
  queries:
    - name: queryCommitStatuses
      query:
        function: queryCommitStatuses
        kind: local
      parameters:
        - name: repository
          value:
            $$jsExpression: |
              page.parameters.repository
  display: standalone
