apiVersion: v1
kind: page
spec:
  id: 9ou3hb2
  title: page
  parameters:
    - name: repoId
      value: "23083156"
  content:
    - component: PageRow
      name: PageRow
      children:
        - component: codeComponent.HealthBadge
          name: codeComponent_HealthBadge
          props:
            value:
              $$jsExpression: >
                (() => {
                  const length = pullRequestOpenToMerged.data.data.length

                  return (
                    Math.round((pullRequestOpenToMerged.data.data[length - 1].p75 / 24) * 100) /
                    100
                  )
                })()
            warning: 3
            problem: 5
            unit: days
            lowerIsBetter: true
    - component: PageRow
      name: PageRow1
      children:
        - component: Text
          name: Text
          props:
            value:
              $$jsExpression: |
                (() => {
                  const length = pullRequestOpenToMerged.data.data.length

                  return `Based on the last 30 days (${
                    pullRequestOpenToMerged.data.data[length - 1].event_month
                  })`
                })()
  queries:
    - name: pullRequestOpenToMerged
      query:
        kind: rest
        url:
          $$jsExpression: >
            `https://api.ossinsight.io/q/analyze-pull-request-open-to-merged?repoId=${parameters.repoId}`
        headers: []
        method: GET
        searchParams: []
      parameters:
        - name: repoId
          value:
            $$jsExpression: |
              page.parameters.repoId
  display: standalone
