# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.1.40/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: needTriage
  parameters:
    - name: repository
      value: material-ui
  content:
    - component: codeComponent.HealthBadge
      name: codeComponent_HealthBadge
      layout:
        columnSize: 1
      props:
        value:
          $$jsExpression: |
            needTriage.data.total_count
        warning: 25
        problem: 50
        unit: ' issues'
        lowerIsBetter: true
  queries:
    - name: needTriage
      query:
        kind: rest
        url: https://api.github.com/search/issues
        searchParams:
          - name: q
            value:
              $$jsExpression: >
                `is:issue repo:mui/${parameters.repository} label:"status: needs
                triage" `
        headers: []
        method: GET
      parameters:
        - name: repository
          value:
            $$jsExpression: |
              page.parameters.repository
  display: shell
  alias:
    - hj1i3hqe
