apiVersion: v1
kind: page
spec:
  id: hj1i3hqe
  title: needTriage
  parameters:
    - name: repository
      value: material-ui
  content:
    - component: PageRow
      name: PageRow
      children:
        - component: codeComponent.HealthBadge
          name: codeComponent_HealthBadge
          props:
            value:
              $$jsExpression: |
                needTriage.data.total_count
            warning: 25
            problem: 50
            unit: " issues"
            lowerIsBetter: true
  queries:
    - name: needTriage
      query:
        kind: rest
        url: https://api.github.com/search/issues
        searchParams:
          - name: q
            value:
              $$jsExpression: >
                `is:issue is:open repo:mui/${parameters.repository}
                label:"status: needs triage" `
        headers: []
        method: GET
      parameters:
        - name: repository
          value:
            $$jsExpression: |
              page.parameters.repository
  display: standalone
