name: Add closing message to issue

on:
  issues:
    types:
      - closed
  workflow_call:

permissions: {}

jobs:
  add-comment:
    runs-on: ubuntu-latest
    name: Check author permission and add closing message
    permissions:
      issues: write
    steps:
      - name: Check out public repo
        uses: actions/checkout@v3
        with:
          # Check this repository out, otherwise the script won't be available,
          # as it checks out the repository where the workflow caller is located
          repository: mui/mui-public
      - name: Add closing comment
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const script = require('./.github/workflows/scripts/addClosingMessage.js')
            await script({core, github, context})
