apiVersion: v1
kind: page
spec:
  id: hl63hwf
  title: needtriageNotAssigned
  content:
    - component: PageRow
      name: pageRow1
      children:
        - component: Text
          name: text1
          props:
            value: Open "need triage" issues without assignee
            variant: h5
    - component: PageRow
      name: pageRow2
      children:
        - component: Text
          name: text2
          props:
            mode: markdown
            value: "Built for:
              https://www.notion.so/mui-org/GitHub-community-issues-PRs-Tier-1-\
              12a84fdf50e44595afc55343dac00fca#8f5ae0daa6ad4543b866f3ad0532c9e4"
    - component: PageRow
      name: pageRow3
      children:
        - component: DataGrid
          name: dataGrid
          props:
            rows:
              $$jsExpression: >
                noAssignee.data
                  .map((data) => ({
                    ...data,
                    repo: data.repository_url.replace("https://api.github.com/repos/mui/", ""),
                  }))
                  .sort((a, b) => {
                    if (a.repo === "mui-x") {
                      return -1
                    }

                    if (b.repo === "mui-x") {
                      return -1
                    }
                  })
            columns:
              - field: number
                type: string
              - field: repo
                type: string
                width: 71
              - field: title
                type: string
                width: 372
              - field: html_url
                type: link
                width: 203
            height: 452
  queries:
    - name: noAssignee
      query:
        kind: rest
        url: https://api.github.com/search/issues
        searchParams:
          - name: q
            value: 'repo:mui/material-ui repo:mui/mui-x is:open is:issue label:"status:
              needs triage" no:assignee'
        headers:
          - name: Bearer
            value: abc
        method: GET
        transform: |+
          return data.items

        transformEnabled: true
