# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.1.40/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: needtriageNotAssigned
  content:
    - component: Text
      name: text1
      layout:
        columnSize: 1
      props:
        value: Open "need triage" issues without assignee
        variant: h5
    - component: Text
      name: text2
      layout:
        columnSize: 1
      props:
        mode: markdown
        value: "Built for:
          https://www.notion.so/mui-org/GitHub-community-issues-PRs-Tier-1-12a8\
          4fdf50e44595afc55343dac00fca#8f5ae0daa6ad4543b866f3ad0532c9e4"
    - component: DataGrid
      name: dataGrid
      layout:
        columnSize: 1
      props:
        rows:
          $$jsExpression: >
            noAssignee.data
              .map((data) => ({
                ...data,
                repo: data.repository_url.replace("https://api.github.com/repos/mui/", ""),
              }))
              .sort((a, b) => {
                if (a.repo === "mui-x") {
                  return -1
                }

                if (b.repo === "mui-x") {
                  return -1
                }
              })
        columns:
          - field: number
            type: string
          - field: repo
            type: string
            width: 109
          - field: title
            type: string
            width: 372
          - field: html_url
            type: link
            width: 203
        height: 452
  queries:
    - name: noAssignee
      query:
        kind: rest
        url: https://api.github.com/search/issues
        searchParams:
          - name: q
            value: 'repo:mui/material-ui repo:mui/mui-x is:open is:issue label:"status:
              waiting for maintainer" no:assignee'
        headers:
          - name: Bearer
            value: abc
        method: GET
        transform: |+
          return data.items

        transformEnabled: true
  alias:
    - hl63hwf
