# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.1.40/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: issueWithoutProductScope
  content:
    - component: Text
      name: text
      layout:
        columnSize: 1
      props:
        value: Issues without product scope label
        variant: h5
    - component: Text
      name: text1
      layout:
        columnSize: 1
      props:
        mode: markdown
        value: "This page is used for:
          https://www.notion.so/mui-org/GitHub-community-issues-PRs-12a84fdf50e\
          44595afc55343dac00fca#d6680f5abf8b4e3ab132cb8e336bb5bc"
    - component: DataGrid
      name: dataGrid
      layout:
        columnSize: 1
      props:
        rows:
          $$jsExpression: |
            (() => {
              const nonProductScopeLabels = [
                "support: commercial",
                "support: docs-feedback",
              ]

              return materialUI.rows
                .concat(muix.rows)
                .concat(muiDesignKits.rows)
                .filter((issue) => {
                  const withoutNonProductScopeLabels = issue.labels.filter(
                    (label) => !nonProductScopeLabels.includes(label.name)
                  )
                  return withoutNonProductScopeLabels.length === 1
                })
                .sort((issueA, issueB) => {
                  if (issueA.state === "open") {
                    return 1
                  }
                  if (issueB.state === "open") {
                    return 1
                  }
                  return issueB.number - issueA.number
                })
            })()
        columns:
          - field: number
            type: string
            width: 74
          - field: state
            type: string
            width: 82
          - field: title
            type: string
            width: 352
          - field: html_url
            type: link
            width: 111
        height: 396
  queries:
    - name: materialUI
      query:
        kind: rest
        url: https://api.github.com/repos/mui/material-ui/issues
        searchParams:
          - name: labels
            value: 'status: needs triage'
          - name: per_page
            value: '100'
          - name: state
            value: all
        headers: []
        method: GET
    - name: muix
      query:
        kind: rest
        url: https://api.github.com/repos/mui/mui-x/issues
        searchParams:
          - name: labels
            value: 'status: needs triage'
          - name: per_page
            value: '100'
          - name: state
            value: all
        headers: [{ name: Authorization, value: { $$env: GITHUB_TOKEN } }]
        method: GET
    - name: muiDesignKits
      query:
        kind: rest
        url: https://api.github.com/repos/mui/mui-design-kits/issues
        searchParams:
          - name: labels
            value: 'status: needs triage'
          - name: per_page
            value: '100'
          - name: state
            value: all
        headers: [{ name: Authorization, value: { $$env: GITHUB_TOKEN } }]
        method: GET
  alias:
    - y923hoo
